"""Phase 3 automation. Revision ID: 0003_phase3_automation Revises: 0002_phase2_ai_pipeline"""
from collections.abc import Sequence
from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
revision: str = "0003_phase3_automation"; down_revision: str | None = "0002_phase2_ai_pipeline"; branch_labels: str | Sequence[str] | None = None; depends_on: str | Sequence[str] | None = None
def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table("job_embeddings", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("job_id", sa.Uuid(), nullable=False), sa.Column("embedding", Vector(768), nullable=False), sa.Column("model_name", sa.String(200), nullable=False), sa.Column("text_hash", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("job_id"))
    op.create_index("ix_job_embeddings_job_id", "job_embeddings", ["job_id"], unique=True); op.execute("CREATE INDEX ix_job_embeddings_hnsw ON job_embeddings USING hnsw (embedding vector_cosine_ops)")
    op.create_table("job_alerts", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("candidate_id", sa.Uuid(), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("keywords", sa.JSON(), nullable=False), sa.Column("locations", sa.JSON(), nullable=False), sa.Column("providers", sa.JSON(), nullable=False), sa.Column("remote_only", sa.Boolean(), nullable=False), sa.Column("min_match_score", sa.Float(), nullable=False), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("last_run_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["candidate_id"], ["candidate_profiles.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id")); op.create_index("ix_job_alerts_candidate_id", "job_alerts", ["candidate_id"]); op.create_index("ix_job_alerts_active", "job_alerts", ["active"])
    op.create_table("job_alert_matches", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("alert_id", sa.Uuid(), nullable=False), sa.Column("job_id", sa.Uuid(), nullable=False), sa.Column("match_score", sa.Float(), nullable=False), sa.Column("recommendation", sa.String(100), nullable=False), sa.Column("notified", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["alert_id"], ["job_alerts.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("alert_id", "job_id", name="uq_job_alert_match")); op.create_index("ix_job_alert_matches_alert_id", "job_alert_matches", ["alert_id"]); op.create_index("ix_job_alert_matches_job_id", "job_alert_matches", ["job_id"])
    op.create_table("recruiter_email_events", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("provider_message_id", sa.String(255), nullable=False), sa.Column("thread_id", sa.String(255)), sa.Column("sender", sa.String(500), nullable=False), sa.Column("subject", sa.Text(), nullable=False), sa.Column("snippet", sa.Text(), nullable=False), sa.Column("category", sa.String(50), nullable=False), sa.Column("company", sa.String(255)), sa.Column("role_title", sa.String(255)), sa.Column("application_id", sa.Uuid()), sa.Column("received_at", sa.DateTime(timezone=True)), sa.Column("processed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("provider_message_id")); op.create_index("ix_recruiter_email_events_provider_message_id", "recruiter_email_events", ["provider_message_id"], unique=True); op.create_index("ix_recruiter_email_events_category", "recruiter_email_events", ["category"])
    op.create_table("interview_preparations", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("candidate_id", sa.Uuid(), nullable=False), sa.Column("job_id", sa.Uuid(), nullable=False), sa.Column("company_summary", sa.Text(), nullable=False), sa.Column("role_summary", sa.Text(), nullable=False), sa.Column("technical_questions", sa.JSON(), nullable=False), sa.Column("behavioral_questions", sa.JSON(), nullable=False), sa.Column("coding_topics", sa.JSON(), nullable=False), sa.Column("system_design_topics", sa.JSON(), nullable=False), sa.Column("candidate_talking_points", sa.JSON(), nullable=False), sa.Column("questions_to_ask", sa.JSON(), nullable=False), sa.Column("ai_used", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["candidate_id"], ["candidate_profiles.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id")); op.create_index("ix_interview_preparations_candidate_id", "interview_preparations", ["candidate_id"]); op.create_index("ix_interview_preparations_job_id", "interview_preparations", ["job_id"])
def downgrade() -> None:
    op.drop_table("interview_preparations"); op.drop_table("recruiter_email_events"); op.drop_table("job_alert_matches"); op.drop_table("job_alerts"); op.execute("DROP INDEX IF EXISTS ix_job_embeddings_hnsw"); op.drop_table("job_embeddings")
